//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterForm
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public  class DanhMucHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucHang()
        {
            this.SanPhams = new HashSet<SanPham>();
        }

        public DanhMucHang(DataRow item)
        {
            Item = item;
            /*this.MaDm = (int)item["MaDm"];
            this.TenDm = item["TenDm"].ToString();*/
        }

        public int MaDm { get; set; }
        public string TenDm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
        public DataRow Item { get; }
        public int ID { get; internal set; }
    }
}
